# 5 PyTorch functions for dummies (like me)


PyTorch is a library specifically designed for numerical computations and building neural networks. While it is widely used, and most of its useful functions are regulary taught and known by beginners, here are some interesting functions I found, reading the documentation:

- TORCH.TENSOR.WHERE
- TORCH.UNBIND
- TORCH.UNIQUE
- TORCH.UNSQUEEZE
- TORCH.TENSOR.INDEX_ADD_



In [ ]:
import torch

## TORCH.TENSOR.WHERE

It is a PyTorch function that returns a new tensor with elements from two input tensors, depending on the values of a condition tensor. It can be used as torch.where().

The operation works as: 

outx = {x, if condition is true,
        y, otherwise}

In [ ]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
print(x)
a = torch.where(x > 0, x, y)
print(a)

tensor([[ 1.5128, -0.4714],
        [-0.7235, -0.5802],
        [ 0.3103, -1.6022]])
tensor([[1.5128, 1.0000],
        [1.0000, 1.0000],
        [0.3103, 1.0000]])


Since the condition is x being positive, every index where x is negative is replaced by y. that is 1.

In [ ]:

a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([6, 7, 8, 9, 10])
condition = torch.tensor([True, False, True, False, True])

result = torch.where(condition, a, b)
print(result)


tensor([1, 7, 3, 9, 5])


Conditions can also be passed as tensors themselves. Our target tensors have length 5, hence we pass a tensor with 5 conditions, which ends up giving the reuired output.

In [ ]:
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([6, 7, 8, 9])
condition = torch.tensor([True, False, True, False, True])

result = torch.where(condition, a, b)
print(result)

RuntimeError: ignored

As you can observe, the size of the second tensor isn't the same as the first tensor, hence it gives us an error.

## TORCH.UNBIND

This function is used to remove a tensor dimension.
It takes in a tensor as input, alongside a dim which specifies a dimension to remove. 

In [ ]:
torch.unbind(torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

As the dimension isn't specified, the default value 0 is taken and the tensors are split along rows,

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.unbind(x, dim = 1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

In [ ]:
torch.unbind(x, dim = 2)

IndexError: ignored

The dimension is set to 2, which is outside the range of dimensions, hence we get an error.

This function should be used when there is a need to split data along rows or columns.

## TORCH.UNIQUE
As the name suggests, it returns the unique elements of the input tensor.It takes the parameters input, sorted, return_inverse, return_counts, dim. It is particularly useful as it helps to sort, find the indices and counts of the unique elements.

In [ ]:
output = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long))
output



tensor([1, 2, 3])

This is s simple illustration of the workings of unique without specifying and parameters.

In [ ]:
output, inverse_indices = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=True, return_inverse=True)
print(output)
print(inverse_indices)


tensor([1, 2, 3])
tensor([0, 2, 1, 2])


This shows the workings of the  various useful parameters that can be used with unique.

In [ ]:
x = torch.tensor([1, 1, 2, 2, 3, 1, 1, 2])
output = torch.unique_consecutive(x)
print(output)

tensor([1, 2, 3, 1, 2])


torch.unique_consecutive is a slightly modified version of torch.unique that is worth mentioning as it has a lot of similarities with torch.unique.

It eliminates all but the first element from every consecutive group of equivalent elements.

In [ ]:
x = torch.tensor([1, 2, 3, 1, 2, 3])
y = torch.unique(x, reverse_sorted=True, return_counts=True)
print(y)

TypeError: ignored

This code snippet gives us an error as we're attempting to sort in a reverse order, but unique doesn't contain a parameter calle reverse_sorted, giving rise to the error.

## TORCH.UNSQUEEZE

This function returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

In [ ]:
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 1))

tensor([[1],
        [2],
        [3],
        [4]])


Our tensor had shape (1,4). The dimension is set to 1, hence the new shape would be (1, 1, 4).

In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
print(torch.unsqueeze(x, 2))

tensor([[[1],
         [2]],

        [[3],
         [4]]])


The original shape was (2, 2). Upon unsqueezing the tensor, the shape ends up being (2, 2, 1)

In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
print(torch.unsqueeze(x, 3))

IndexError: ignored

In this case, obviously the shape of our tensor is (2, 2), and we're asking PyTorch to add a new dimension at index 3, which gives us an error.

## TORCH.TENSOR.INDEX_ADD_

This function is used to perform in-place addition between a tensor and another tensor with a subset of its values, selected by an index tensor. which takes parameters, dim, index, source, and  alpha. 

Dim is the dimension aong which the addition needs to be perfomred.

self[index[i], :, :] += alpha * src[i, :, :]  # if dim == 0

self[:, index[i], :] += alpha * src[:, i, :]  # if dim == 1

self[:, :, index[i]] += alpha * src[:, :, i]  # if dim == 2



In [ ]:
x = torch.ones(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
print(x.index_add_(0, index, t))
#x.index_add_(0, index, t, alpha=-1)

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])


According to the index tensor, the 0th row gets individually added to the first row of the 't' tensor. Hence the ouput is 1+1=2, 1+2=3, 1+3=4.
The 1st and 3rd indices are left unchanged as they are not mentioned in the index tensor. 

Similar to the 0th row, the 5th row (4th index) and the 3rd row(2nd index) get respectivelly added to the 2nd and 3rd row of the 't' tensor.

In [ ]:
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
print(x.index_add_(0, index, t, alpha = -1))

tensor([[-1., -2., -3.],
        [ 0.,  0.,  0.],
        [-7., -8., -9.],
        [ 0.,  0.,  0.],
        [-4., -5., -6.]])


This example is identical to the 1st example, apart from the fact that alpha is set to -1 which signifies that the tensor 't' will be subtracted instead if getting added to the tensor 'x'.

In [ ]:
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
print(x.index_add_(0, index, t, alpha = -1))

RuntimeError: ignored

As you can clearly see, the size of the tensor 't' and ad the number of inidices aren't equal, giving rise to an obvious error.

## Conclusion

I hope you had as much fun reading about these functions as I had. The source for all of them is the official PyTorch documentation. The next step for me, and for my fellow dummies should be to use more of these functions in our everyday projects, trying to make life easier.

For example, if you want to select rows from a multi-dimensional tensor, you can run a for loop, and get the values you're looking for, but how about trying torch.tensor.unbind?

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [ ]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 KB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations-assignment-01')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
